#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
module VagrantPlugins
  module Xhyve
    module Support
      class DhcpdLeases < Racc::Parser

module_eval(<<'...end dhcpd_leases.y/module_eval...', 'dhcpd_leases.y', 12)

def parse(str)
  @str = str
  yyparse self, :scan
end

private

def scan
  str = @str

  until str.empty?
    case str
    when /\A\s+/
      str = $'
    when /\A[\w\.\,\:]+/
      yield([:IDENT, $&])
      str = $'
    else
      c = str[0, 1]
      yield([c, c])
      str = str[1..-1]
    end
  end

  yield([false, '$'])
end
...end dhcpd_leases.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     3,     2,     4,     9,    10,    12,    10,     6,     7,    11,
     6,    13,    14,    15 ]

racc_action_check = [
     1,     0,     1,     5,     5,     8,     8,     4,     3,     6,
     2,    10,    11,    13 ]

racc_action_pointer = [
    -1,     0,     6,     8,     3,     0,     4,   nil,     2,   nil,
     6,     8,   nil,     9,   nil,   nil ]

racc_action_default = [
    -5,    -5,    -5,    -5,    -5,    -5,    -5,    16,    -5,    -1,
    -5,    -5,    -2,    -5,    -3,    -4 ]

racc_goto_table = [
     5,     1,     8 ]

racc_goto_check = [
     2,     1,     2 ]

racc_goto_pointer = [
   nil,     1,    -2 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 7, :_reduce_1,
  4, 7, :_reduce_2,
  3, 8, :_reduce_3,
  4, 8, :_reduce_4 ]

racc_reduce_n = 5

racc_shift_n = 16

racc_token_table = {
  false => 0,
  :error => 1,
  "{" => 2,
  "}" => 3,
  :IDENT => 4,
  "=" => 5 }

racc_nt_base = 6

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"{\"",
  "\"}\"",
  "IDENT",
  "\"=\"",
  "$start",
  "blocks",
  "body" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'dhcpd_leases.y', 4)
  def _reduce_1(val, _values, result)
     result = [val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'dhcpd_leases.y', 5)
  def _reduce_2(val, _values, result)
     result = result.push(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'dhcpd_leases.y', 7)
  def _reduce_3(val, _values, result)
     result = {val[0] => val[2]} 
    result
  end
.,.,

module_eval(<<'.,.,', 'dhcpd_leases.y', 8)
  def _reduce_4(val, _values, result)
     result[val[1]] = val[3] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

      end   # class DhcpdLeases
      end   # module Support
    end   # module Xhyve
  end   # module VagrantPlugins
